# Site settings
author: Milagro Flores
title: Why I decided to learn Software Engineering.
header-img: img/home-bg.png
email: miflo0h@gmail.com
copyright_name: Milagro Flores
description: > # this means to ignore newlines until "baseurl:"
  *
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  mil999f

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
